name: Firebase excel importer

on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 5 * * *' # Todos los días a las 5:00 am

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run project
        run: |
          python main.py \
            --bucket ${{ vars.BUCKET }} \
            --blob ${{ vars.BLOB }} \
            --path ${{ vars.PATH_FILE }} \
            --destination ${{ vars.DESTINATION }} \
            --type ${{ vars.TYPE }} \
            --project-id ${{ vars.PROJECT_ID }} \
            --private-key-id ${{ vars.PRIVATE_KEY_ID }} \
            --private-key "${{ vars.PRIVATE_KEY }}" \
            --client-email ${{ vars.CLIENT_EMAIL }} \
            --client-id ${{ vars.CLIENT_ID }} \
            --auth-uri ${{ vars.AUTH_URI }} \
            --token-uri ${{ vars.TOKEN_URI }} \
            --auth-provider-x509-cert-url ${{ vars.AUTH_PROVIDER_X509_CERT_URL }} \
            --client-x509-cert-url ${{ vars.CLIENT_X509_CERT_URL }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
