name: Firebase excel importer

on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 5 * * *' # Todos los días a las 5:00 am

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run project
        env:
          TYPE: ${{ vars.TYPE }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ vars.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ vars.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ vars.CLIENT_EMAIL }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          AUTH_URI: ${{ vars.AUTH_URI }}
          TOKEN_URI: ${{ vars.TOKEN_URI }}
          AUTH_PROVIDER_X509_CERT_URL: ${{ vars.AUTH_PROVIDER_X509_CERT_URL }}
          CLIENT_X509_CERT_URL: ${{ vars.CLIENT_X509_CERT_URL }}
          BUCKET: ${{ vars.BUCKET }}
          BLOB: ${{ vars.BLOB }}
          PATH_FILE: ${{ vars.PATH_FILE }}
          DESTINATION: ${{ vars.DESTINATION }}
        run: python main.py


      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
